version: "3.8"

services:
  db:
    image: postgres:14
    container_name: vopc_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "15432:5432"

  odoo:
    image: odoo:18.0
    container_name: vopc_odoo
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - "8069:8069"
    environment:
      HOST: db
      USER: odoo
      PASSWORD: odoo
    volumes:
      - odoo-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons
      - ./config/odoo.conf:/etc/odoo/odoo.conf

  mailhog:
    image: mailhog/mailhog
    container_name: vopc_mail
    restart: unless-stopped
    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  pgdata:
  odoo-data:
