[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
workers = 0
admin_passwd = $pbkdf2-sha512$600000$6t2bM8Z4b00JgdCa07o3Rg$QHojDXcpSK2z2dldMfqoeABZryWGbYqzr0Bbcrd8r.5mSOJWJCLMiheMctlkBRF6CoX4S/nPO0hrNPEisafakg

