[options]
addons_path = /mnt/extra-addons
data_dir = /var/lib/odoo
admin_passwd = $pbkdf2-sha512$600000$6H3P2ZtzjhHCeO997z2HUA$uQkqhGISwA1do9ec5xCm2IAi.azf4jlptExAh3sUS.AXYLRK6C8568AlPrjtNu6EtrWYJgHQ30.xtANaELeyQg

