[options]
addons_path = /mnt/extra-addons,/usr/lib/python3/dist-packages/odoo/addons
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo
workers = 0
admin_passwd = $pbkdf2-sha512$600000$w3hPSSmFkNLa.58zplSK8Q$0y7Ql82b6qvjM2uBVXaG0AWU0M9JoGCdsjmO5xAQiBKyia9fQGHflRgykNDNAoA0OxbmfevphKtxve9pMEFgrA

